# Generated by Django 3.1.5 on 2021-01-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateTimeField()),
                ('facility_no', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('unit_id', models.CharField(max_length=100)),
                ('imms', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=100)),
                ('mfr_cat_no', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=0)),
                ('cost', models.FloatField()),
                ('uom', models.CharField(max_length=50)),
                ('ext', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-ext',),
            },
        ),
    ]
