# Generated by Django 3.1.5 on 2021-01-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_issue_purchaseorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invcount',
            old_name='facility_no',
            new_name='fac',
        ),
    ]
