# Generated by Django 3.1.5 on 2021-01-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210107_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invcount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='created_at',
        ),
    ]
