# Generated by Django 3.1.5 on 2021-01-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210107_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invcount',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invcount',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invcount',
            name='ext',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invcount',
            name='mfr_cat_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invcount',
            name='unit_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invcount',
            name='uom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invcount',
            name='vendor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
