# Generated by Django 3.1.5 on 2021-01-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210107_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='facility_no',
            new_name='facility_number',
        ),
    ]
