# Generated by Django 3.1.5 on 2021-01-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210107_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countusagelist',
            options={'ordering': ('-default_uom_price',)},
        ),
    ]
