# Generated by Django 3.1.5 on 2021-01-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210107_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountUsageList',
        ),
    ]
